In [2]:
import numpy as np
import pandas as pd 

df=pd.read_csv('supermarket_sales.csv')

unit_price=df[['Unit price']].to_numpy()
quantity=df[['Quantity']].to_numpy()

unit_price[:10,0]

array([74.69, 15.28, 46.33, 58.22, 86.31, 85.39, 68.84, 73.56, 36.26,
       54.84])

In [11]:
quantity[:20,0]

array([ 7,  5,  7,  8,  7,  7,  6, 10,  2,  3,  4,  4,  5, 10, 10,  6,  7,
        6,  3,  2])

In [17]:
#media de unit_price
media_price=unit_price.mean()
format_media='{:.2f}'.format(media_price)
print('La media de Unit price es: ', format_media)

La media de Unit price es:  55.67


In [18]:
#media de quantity
media_quantity=quantity.mean()
format_quantity='{:.2f}'.format(media_quantity)
print('La media de Quantity es: ', format_quantity)

La media de Quantity es:  5.51


In [27]:
#mediana de unit price
mediana_price=np.median(unit_price)
print(f'La mediana de unit price es = {mediana_price:.2f}')

La mediana de unit price es = 55.23


In [28]:
#mediana
mediana_quantity=np.median(quantity)
print(f'La mediana de quantity es = {mediana_quantity:.2f}')

La mediana de quantity es = 5.00


In [29]:
#moda de unit price
vals, counts= np.unique(unit_price, return_counts=True)
index=np.argmax(counts)
moda=vals[index] 
print(f'La modad de la unit price es = {moda:.2f}')

La modad de la unit price es = 83.77


In [30]:
#moda de quantity
vals1, counts1= np.unique(quantity, return_counts=True)
index=np.argmax(counts1)
moda1=vals1[index] 
print(f'La modad de la quantity es = {moda1:.2f}')

La modad de la quantity es = 10.00


In [38]:
#Ticket primedio por ciudad
prom_ciudad=df.groupby('City')['Total'].mean()
prom_ciudad

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Total, dtype: float64

In [44]:
#Ticket primedio por product line y ciudad
prom_ciudad_product=df.groupby(['City', 'Product line'])['Total'].mean()
prom_ciudad_product

City       Product line          
Mandalay   Electronic accessories    310.026245
           Fashion accessories       264.730911
           Food and beverages        304.297770
           Health and beauty         376.993585
           Home and lifestyle        350.983290
           Sports and travel         322.390306
Naypyitaw  Electronic accessories    344.890445
           Fashion accessories       331.693385
           Food and beverages        360.103864
           Health and beauty         319.525500
           Home and lifestyle        308.790067
           Sports and travel         350.265067
Yangon     Electronic accessories    305.285225
           Fashion accessories       320.245265
           Food and beverages        295.915526
           Health and beauty         268.037298
           Home and lifestyle        344.879931
           Sports and travel         328.350839
Name: Total, dtype: float64

In [ ]:
#Ticket primedio por genero
prom_genero=df.groupby('Gender')['Total'].mean()
prom_genero

Gender
Female    335.095659
Male      310.789226
Name: Total, dtype: float64

In [51]:
#Ticket primedio por genero y product line 
prom_genero_product=df.groupby(['Gender', 'Product line'])['Total'].mean()
prom_genero_product

Gender  Product line          
Female  Electronic accessories    322.643125
        Fashion accessories       317.056250
        Food and beverages        368.565750
        Health and beauty         290.015414
        Home and lifestyle        380.213639
        Sports and travel         324.712739
Male    Electronic accessories    316.691965
        Fashion accessories       291.079207
        Food and beverages        273.499125
        Health and beauty         348.099460
        Home and lifestyle        294.136241
        Sports and travel         340.360327
Name: Total, dtype: float64

In [ ]:
#Top 5 ventas por ciudad
df['ranking']=df.groupby('City')['Total'].rank(ascending=False)
top_5=df[df['ranking']<=5][['City', 'Total', 'ranking']]
top_5=top_5.sort_values(by=['City','ranking'], ascending=[True, False])
print(top_5)

          City      Total  ranking
96    Mandalay   922.6350      5.0
209   Mandalay   942.4485      4.0
122   Mandalay   944.6220      3.0
792   Mandalay  1022.3850      2.0
996   Mandalay  1022.4900      1.0
166  Naypyitaw  1003.5900      5.0
422  Naypyitaw  1020.7050      4.0
699  Naypyitaw  1023.7500      3.0
557  Naypyitaw  1034.4600      2.0
350  Naypyitaw  1042.6500      1.0
529     Yangon   926.9505      5.0
105     Yangon   931.0350      4.0
959     Yangon   932.3370      3.0
429     Yangon   951.8250      2.0
167     Yangon  1039.2900      1.0


In [87]:
#Top 5 ventas por member
miembros=df[df['Customer type']=='Member']
ventas_m=miembros.groupby('Payment')['Total'].sum().reset_index()
ventas_m['ranking']=ventas_m['Total'].rank(ascending=False)
top_5m=ventas_m[ventas_m['ranking']<=5]
top_5m=top_5m.sort_values(by='ranking', ascending=False)
print(top_5m)

       Payment       Total  ranking
2      Ewallet  51790.9560      3.0
0         Cash  54661.0155      2.0
1  Credit card  57771.4725      1.0


In [ ]:
#Top 5 ventas por payment
df['ranking']=df.groupby('Payment')['Total'].rank(ascending=False)
top_5p=df[df['ranking']<=5][['Payment', 'Total', 'ranking']]
top_5p=top_5p.sort_values(by=['Payment','Total','ranking'], ascending=[True, False, False])
print(top_5p)

         Payment      Total  ranking
166         Cash  1003.5900      1.0
357         Cash  1002.1200      2.0
141         Cash   950.2500      3.0
941         Cash   943.2990      4.0
611         Cash   935.2665      5.0
350  Credit card  1042.6500      1.0
167  Credit card  1039.2900      2.0
792  Credit card  1022.3850      3.0
422  Credit card  1020.7050      4.0
122  Credit card   944.6220      5.0
557      Ewallet  1034.4600      1.0
699      Ewallet  1023.7500      2.0
996      Ewallet  1022.4900      3.0
429      Ewallet   951.8250      4.0
435      Ewallet   937.8180      5.0


In [ ]:
#matriz de correlacion de tiempo (sin minutos) y total
tiempo=df[['Time']].to_numpy()
horas=np.array([int(h[0].split(':')[0]) for h in tiempo])
total=df[['Total']].to_numpy()
total_b=total.flatten()
total_b
c=np.corrcoef(horas, total_b)
c


array([[ 1.        , -0.00277044],
       [-0.00277044,  1.        ]])

In [30]:
#matriz de correlacion entre unit price y rating
unit_price_b=unit_price.flatten()
raten=df[['Rating']].to_numpy()
raten_b=raten.flatten()
r=np.corrcoef(unit_price_b, raten_b)
r

array([[ 1.        , -0.00877751],
       [-0.00877751,  1.        ]])